# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aa\Desktop\CodeRefonte\Interface\interface.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 600))
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(:/Fond/gg.png);\n"
"}\n"
"")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab.setEnabled(True)
        self.Tab.setGeometry(QtCore.QRect(230, 30, 731, 521))
        self.Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tab.setObjectName("Tab")
        self.Tab_runing = QtWidgets.QWidget()
        self.Tab_runing.setObjectName("Tab_runing")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Tab_runing)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 721, 481))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.Running_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.Running_4.setContentsMargins(0, 0, 0, 0)
        self.Running_4.setObjectName("Running_4")
        self.View_2 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.View_2.setEnabled(True)
        self.View_2.setMinimumSize(QtCore.QSize(0, 250))
        self.View_2.setObjectName("View_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.View_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 221, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.quality = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.quality.setEnabled(False)
        self.quality.setObjectName("quality")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.quality)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_40.setObjectName("label_40")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.iteration = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.iteration.setEnabled(False)
        self.iteration.setObjectName("iteration")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.iteration)
        self.label_48 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_48.setObjectName("label_48")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.tresh = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.tresh.setEnabled(False)
        self.tresh.setObjectName("tresh")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tresh)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_41.setObjectName("label_41")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.alpha = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.alpha.setEnabled(True)
        self.alpha.setObjectName("alpha")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.alpha)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_42.setObjectName("label_42")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.time = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.time.setEnabled(False)
        self.time.setObjectName("time")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.time)
        self.population = QtWidgets.QTabWidget(self.View_2)
        self.population.setEnabled(True)
        self.population.setGeometry(QtCore.QRect(250, 19, 451, 231))
        self.population.setObjectName("population")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.list_identity = QtWidgets.QListWidget(self.tab_2)
        self.list_identity.setEnabled(True)
        self.list_identity.setGeometry(QtCore.QRect(10, 10, 421, 191))
        self.list_identity.setObjectName("list_identity")
        self.population.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.list_incarnation = QtWidgets.QListWidget(self.tab_3)
        self.list_incarnation.setEnabled(True)
        self.list_incarnation.setGeometry(QtCore.QRect(10, 10, 421, 191))
        self.list_incarnation.setObjectName("list_incarnation")
        self.population.addTab(self.tab_3, "")
        self.Subset = QtWidgets.QWidget()
        self.Subset.setObjectName("Subset")
        self.list_subset = QtWidgets.QListWidget(self.Subset)
        self.list_subset.setEnabled(True)
        self.list_subset.setGeometry(QtCore.QRect(10, 10, 421, 191))
        self.list_subset.setObjectName("list_subset")
        self.population.addTab(self.Subset, "")
        self.Running_4.addWidget(self.View_2)
        self.Edit_2 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self.Edit_2.setEnabled(True)
        self.Edit_2.setMinimumSize(QtCore.QSize(0, 223))
        self.Edit_2.setMaximumSize(QtCore.QSize(16777215, 223))
        self.Edit_2.setObjectName("Edit_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Edit_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 727, 212))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.show_time = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.show_time.setMinimumSize(QtCore.QSize(0, 30))
        self.show_time.setObjectName("show_time")
        self.verticalLayout_2.addWidget(self.show_time)
        self.show_alpha_incarnation = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.show_alpha_incarnation.setMinimumSize(QtCore.QSize(0, 30))
        self.show_alpha_incarnation.setObjectName("show_alpha_incarnation")
        self.verticalLayout_2.addWidget(self.show_alpha_incarnation)
        self.show_tabou_list = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.show_tabou_list.setMinimumSize(QtCore.QSize(0, 30))
        self.show_tabou_list.setObjectName("show_tabou_list")
        self.verticalLayout_2.addWidget(self.show_tabou_list)
        self.show_animation = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.show_animation.setMinimumSize(QtCore.QSize(0, 30))
        self.show_animation.setObjectName("show_animation")
        self.verticalLayout_2.addWidget(self.show_animation)
        self.sequential_run = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.sequential_run.setMinimumSize(QtCore.QSize(0, 30))
        self.sequential_run.setObjectName("sequential_run")
        self.verticalLayout_2.addWidget(self.sequential_run)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_28.setMinimumSize(QtCore.QSize(130, 0))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_3.addWidget(self.label_28)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.run = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.run.setObjectName("run")
        self.verticalLayout_4.addWidget(self.run)
        self.cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel.setEnabled(False)
        self.cancel.setObjectName("cancel")
        self.verticalLayout_4.addWidget(self.cancel)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.metrics = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.metrics.setEnabled(True)
        self.metrics.setObjectName("metrics")
        self.verticalLayout_4.addWidget(self.metrics)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.max_iteration = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.max_iteration.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_iteration.setObjectName("max_iteration")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.max_iteration)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.nb_cluster = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.nb_cluster.setMaximumSize(QtCore.QSize(70, 16777215))
        self.nb_cluster.setObjectName("nb_cluster")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nb_cluster)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_29.setMinimumSize(QtCore.QSize(130, 0))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_3.addWidget(self.label_29)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.train_all_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.train_all_2.setMinimumSize(QtCore.QSize(0, 30))
        self.train_all_2.setObjectName("train_all_2")
        self.verticalLayout_3.addWidget(self.train_all_2)
        self.train_all = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.train_all.setMinimumSize(QtCore.QSize(0, 30))
        self.train_all.setObjectName("train_all")
        self.verticalLayout_3.addWidget(self.train_all)
        self.random_initalisation = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.random_initalisation.setMinimumSize(QtCore.QSize(0, 30))
        self.random_initalisation.setObjectName("random_initalisation")
        self.verticalLayout_3.addWidget(self.random_initalisation)
        self.only_global_crossing = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.only_global_crossing.setMinimumSize(QtCore.QSize(0, 30))
        self.only_global_crossing.setObjectName("only_global_crossing")
        self.verticalLayout_3.addWidget(self.only_global_crossing)
        self.evolve_strategies = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.evolve_strategies.setMinimumSize(QtCore.QSize(0, 30))
        self.evolve_strategies.setObjectName("evolve_strategies")
        self.verticalLayout_3.addWidget(self.evolve_strategies)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.Running_4.addWidget(self.Edit_2)
        self.Tab.addTab(self.Tab_runing, "")
        self.Tab_tresholding = QtWidgets.QWidget()
        self.Tab_tresholding.setObjectName("Tab_tresholding")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.Tab_tresholding)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 10, 721, 481))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.Treshodling = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.Treshodling.setContentsMargins(0, 0, 0, 0)
        self.Treshodling.setObjectName("Treshodling")
        self.View = QtWidgets.QWidget(self.verticalLayoutWidget_7)
        self.View.setEnabled(True)
        self.View.setMinimumSize(QtCore.QSize(0, 250))
        self.View.setStyleSheet("QWidget{\n"
"background:black;\n"
"}")
        self.View.setObjectName("View")
        self.rapport = QtWidgets.QListWidget(self.View)
        self.rapport.setEnabled(True)
        self.rapport.setGeometry(QtCore.QRect(160, 30, 421, 191))
        self.rapport.setStyleSheet("QListWidget{\n"
"background-image: url(:/Fond/pic.jpg);\n"
"}")
        self.rapport.setObjectName("rapport")
        self.Treshodling.addWidget(self.View)
        self.Edit = QtWidgets.QWidget(self.verticalLayoutWidget_7)
        self.Edit.setEnabled(True)
        self.Edit.setMinimumSize(QtCore.QSize(0, 223))
        self.Edit.setMaximumSize(QtCore.QSize(16777215, 223))
        self.Edit.setObjectName("Edit")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Edit)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 711, 201))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_31.setMinimumSize(QtCore.QSize(30, 0))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_4.addWidget(self.label_31)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.treshold_type = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.treshold_type.setMinimumSize(QtCore.QSize(130, 0))
        self.treshold_type.setObjectName("treshold_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.treshold_type)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.heuristic_test = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.heuristic_test.setObjectName("heuristic_test")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.heuristic_test)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_18.setEnabled(False)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_33.setEnabled(False)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.per_heuristic = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.per_heuristic.setStyleSheet("QMainWindow{\n"
"background:red\n"
"}")
        self.per_heuristic.setObjectName("per_heuristic")
        self.verticalLayout_6.addWidget(self.per_heuristic)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_2.addWidget(self.label_37)
        self.per_heuristic_iteration = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.per_heuristic_iteration.setObjectName("per_heuristic_iteration")
        self.horizontalLayout_2.addWidget(self.per_heuristic_iteration)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.per_treshold = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.per_treshold.setObjectName("per_treshold")
        self.verticalLayout_6.addWidget(self.per_treshold)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nb_sbudivisions = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.nb_sbudivisions.setObjectName("nb_sbudivisions")
        self.gridLayout_3.addWidget(self.nb_sbudivisions, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setVerticalSpacing(14)
        self.formLayout_3.setObjectName("formLayout_3")
        self.union_treshold_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.union_treshold_label.setEnabled(False)
        self.union_treshold_label.setObjectName("union_treshold_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.union_treshold_label)
        self.nb_tresholding_union = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.nb_tresholding_union.setEnabled(False)
        self.nb_tresholding_union.setObjectName("nb_tresholding_union")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nb_tresholding_union)
        self.unique_treshold_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.unique_treshold_label.setEnabled(False)
        self.unique_treshold_label.setObjectName("unique_treshold_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.unique_treshold_label)
        self.nb_tresholding_unique = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.nb_tresholding_unique.setEnabled(False)
        self.nb_tresholding_unique.setObjectName("nb_tresholding_unique")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nb_tresholding_unique)
        self.manual_treshold_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.manual_treshold_label.setObjectName("manual_treshold_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.manual_treshold_label)
        self.manual_treshold = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.manual_treshold.setObjectName("manual_treshold")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.manual_treshold)
        self.f1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.f1.setEnabled(False)
        self.f1.setObjectName("f1")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.f1)
        self.f2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.f2.setEnabled(False)
        self.f2.setObjectName("f2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.f2)
        self.f3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.f3.setEnabled(False)
        self.f3.setObjectName("f3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.f3)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_16.setEnabled(False)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_25.setEnabled(False)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_17.setEnabled(False)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_32.setMinimumSize(QtCore.QSize(50, 0))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_4.addWidget(self.label_32)
        self.Treshodling.addWidget(self.Edit)
        self.Tab.addTab(self.Tab_tresholding, "")
        self.Tab_generation = QtWidgets.QWidget()
        self.Tab_generation.setObjectName("Tab_generation")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.Tab_generation)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(0, 10, 721, 481))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.genration = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.genration.setContentsMargins(0, 0, 0, 0)
        self.genration.setObjectName("genration")
        self.View_3 = QtWidgets.QWidget(self.verticalLayoutWidget_10)
        self.View_3.setEnabled(True)
        self.View_3.setMinimumSize(QtCore.QSize(0, 250))
        self.View_3.setObjectName("View_3")
        self.genration.addWidget(self.View_3)
        self.Edit_3 = QtWidgets.QWidget(self.verticalLayoutWidget_10)
        self.Edit_3.setEnabled(True)
        self.Edit_3.setMinimumSize(QtCore.QSize(0, 223))
        self.Edit_3.setMaximumSize(QtCore.QSize(16777215, 223))
        self.Edit_3.setObjectName("Edit_3")
        self.genration.addWidget(self.Edit_3)
        self.Tab.addTab(self.Tab_generation, "")
        self.Preprocessing = QtWidgets.QWidget()
        self.Preprocessing.setObjectName("Preprocessing")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.Preprocessing)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(0, 10, 721, 481))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.Preprocessing_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.Preprocessing_2.setContentsMargins(0, 0, 0, 0)
        self.Preprocessing_2.setObjectName("Preprocessing_2")
        self.View_4 = QtWidgets.QWidget(self.verticalLayoutWidget_11)
        self.View_4.setEnabled(True)
        self.View_4.setMinimumSize(QtCore.QSize(0, 250))
        self.View_4.setObjectName("View_4")
        self.Preprocessing_2.addWidget(self.View_4)
        self.Edit_4 = QtWidgets.QWidget(self.verticalLayoutWidget_11)
        self.Edit_4.setEnabled(True)
        self.Edit_4.setMinimumSize(QtCore.QSize(0, 223))
        self.Edit_4.setMaximumSize(QtCore.QSize(16777215, 223))
        self.Edit_4.setObjectName("Edit_4")
        self.Preprocessing_2.addWidget(self.Edit_4)
        self.Tab.addTab(self.Preprocessing, "")
        self.tab_dataset = QtWidgets.QWidget()
        self.tab_dataset.setObjectName("tab_dataset")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tab_dataset)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(0, 10, 721, 481))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.Dataset = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.Dataset.setContentsMargins(0, 0, 0, 0)
        self.Dataset.setObjectName("Dataset")
        self.View_5 = QtWidgets.QWidget(self.verticalLayoutWidget_12)
        self.View_5.setEnabled(True)
        self.View_5.setMinimumSize(QtCore.QSize(0, 250))
        self.View_5.setObjectName("View_5")
        self.Dataset.addWidget(self.View_5)
        self.Edit_5 = QtWidgets.QWidget(self.verticalLayoutWidget_12)
        self.Edit_5.setEnabled(True)
        self.Edit_5.setMinimumSize(QtCore.QSize(0, 223))
        self.Edit_5.setMaximumSize(QtCore.QSize(16777215, 223))
        self.Edit_5.setObjectName("Edit_5")
        self.Dataset.addWidget(self.Edit_5)
        self.Tab.addTab(self.tab_dataset, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Tab.addTab(self.tab, "")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(490, 0, 302, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Navigation = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Navigation.setContentsMargins(0, 0, 0, 0)
        self.Navigation.setSpacing(0)
        self.Navigation.setObjectName("Navigation")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.Navigation.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.Navigation.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.Navigation.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.Navigation.addWidget(self.pushButton_4)
        self.S = QtWidgets.QWidget(self.centralwidget)
        self.S.setGeometry(QtCore.QRect(10, -40, 221, 591))
        self.S.setObjectName("S")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.S)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 50, 211, 531))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Parametres = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Parametres.setContentsMargins(0, 0, 0, 0)
        self.Parametres.setObjectName("Parametres")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.prob_stop = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.prob_stop.setObjectName("prob_stop")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.prob_stop)
        self.prob_supp = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.prob_supp.setObjectName("prob_supp")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.prob_supp)
        self.max_population = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.max_population.setObjectName("max_population")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.max_population)
        self.max_attribute = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.max_attribute.setObjectName("max_attribute")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_attribute)
        self.nb_promotions = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.nb_promotions.setObjectName("nb_promotions")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nb_promotions)
        self.tol_evolutivite = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tol_evolutivite.setObjectName("tol_evolutivite")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tol_evolutivite)
        self.verticalLayout.addLayout(self.formLayout_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.heuristics = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.heuristics.setObjectName("heuristics")
        self.verticalLayout.addWidget(self.heuristics)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.clear.setBaseSize(QtCore.QSize(0, 10))
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.delete_h = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.delete_h.setBaseSize(QtCore.QSize(0, 10))
        self.delete_h.setObjectName("delete_h")
        self.horizontalLayout.addWidget(self.delete_h)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.add_heuristics = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.add_heuristics.setObjectName("add_heuristics")
        self.verticalLayout.addWidget(self.add_heuristics)
        self.heuristics_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.heuristics_button.setObjectName("heuristics_button")
        self.verticalLayout.addWidget(self.heuristics_button)
        self.Parametres.addLayout(self.verticalLayout)
        self.frame = QtWidgets.QFrame(self.S)
        self.frame.setGeometry(QtCore.QRect(210, 40, 621, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.P = QtWidgets.QWidget(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(959, 0, 241, 551))
        self.P.setObjectName("P")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.P)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 238, 531))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Strategie = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Strategie.setContentsMargins(0, 0, 0, 0)
        self.Strategie.setObjectName("Strategie")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.Strategie.addWidget(self.label_10)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.prob_c = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_c.setObjectName("prob_c")
        self.gridLayout.addWidget(self.prob_c, 1, 1, 1, 1)
        self.prob_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_i.setObjectName("prob_i")
        self.gridLayout.addWidget(self.prob_i, 1, 3, 1, 1)
        self.prob_o = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_o.setObjectName("prob_o")
        self.gridLayout.addWidget(self.prob_o, 1, 4, 1, 1)
        self.prob_m = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.prob_m.setObjectName("prob_m")
        self.gridLayout.addWidget(self.prob_m, 1, 2, 1, 1)
        self.Strategie.addLayout(self.gridLayout)
        self.add_strategy = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.add_strategy.setObjectName("add_strategy")
        self.Strategie.addWidget(self.add_strategy)
        self.strategies = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.strategies.setObjectName("strategies")
        self.strategies.setColumnCount(0)
        self.strategies.setRowCount(0)
        self.strategies.horizontalHeader().setDefaultSectionSize(59)
        self.Strategie.addWidget(self.strategies)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.Strategie.addWidget(self.label_15)
        self.training_model = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.training_model.setObjectName("training_model")
        self.Strategie.addWidget(self.training_model)
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.Strategie.addWidget(self.label_39)
        self.ballot = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.ballot.setObjectName("ballot")
        self.Strategie.addWidget(self.ballot)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.Strategie.addWidget(self.label_38)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setEnabled(True)
        self.label_24.setObjectName("label_24")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.tol = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.tol.setEnabled(False)
        self.tol.setObjectName("tol")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tol)
        self.Strategie.addLayout(self.formLayout_6)
        self.S.raise_()
        self.Tab.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.P.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdition = QtWidgets.QMenu(self.menubar)
        self.menuEdition.setObjectName("menuEdition")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(1)
        self.population.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HyperHeuristic"))
        self.label_30.setText(_translate("MainWindow", "Quality"))
        self.label_40.setText(_translate("MainWindow", "iteration                   "))
        self.label_48.setText(_translate("MainWindow", "Treshold"))
        self.label_41.setText(_translate("MainWindow", "Alpha"))
        self.label_42.setText(_translate("MainWindow", "Time"))
        self.population.setTabText(self.population.indexOf(self.tab_2), _translate("MainWindow", "Identity"))
        self.population.setTabText(self.population.indexOf(self.tab_3), _translate("MainWindow", "Incarnation"))
        self.population.setTabText(self.population.indexOf(self.Subset), _translate("MainWindow", "Subset"))
        self.show_time.setText(_translate("MainWindow", "Show time"))
        self.show_alpha_incarnation.setText(_translate("MainWindow", "Show alpha incarnation"))
        self.show_tabou_list.setText(_translate("MainWindow", "Show tabou list"))
        self.show_animation.setText(_translate("MainWindow", "Show animation"))
        self.sequential_run.setText(_translate("MainWindow", "Sequential run"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_22.setText(_translate("MainWindow", "Max.Iteration      "))
        self.label_23.setText(_translate("MainWindow", "Nb.Cluster"))
        self.train_all_2.setText(_translate("MainWindow", "Manuel_generation        "))
        self.train_all.setText(_translate("MainWindow", "Train all"))
        self.random_initalisation.setText(_translate("MainWindow", "Random initialisation    "))
        self.only_global_crossing.setText(_translate("MainWindow", "Only global crossing"))
        self.evolve_strategies.setText(_translate("MainWindow", "Evolve strategies"))
        self.Tab.setTabText(self.Tab.indexOf(self.Tab_runing), _translate("MainWindow", "Running             "))
        self.label_19.setText(_translate("MainWindow", "Tresholding type   "))
        self.label_5.setText(_translate("MainWindow", "Regulation type"))
        self.label_9.setText(_translate("MainWindow", "Heuristic for test"))
        self.label_18.setText(_translate("MainWindow", "Param.1"))
        self.label_33.setText(_translate("MainWindow", "Param.2"))
        self.per_heuristic.setText(_translate("MainWindow", "Per heuristic"))
        self.label_37.setText(_translate("MainWindow", "nb.Iterations            "))
        self.per_treshold.setText(_translate("MainWindow", "Per Treshold"))
        self.label_34.setText(_translate("MainWindow", "Nbr.Subdivisions       "))
        self.union_treshold_label.setText(_translate("MainWindow", "Nb.Iteration.treshold(union) "))
        self.unique_treshold_label.setText(_translate("MainWindow", "Nb.Iteration.treshold(unique)"))
        self.manual_treshold_label.setText(_translate("MainWindow", "Manual treshold"))
        self.label_16.setText(_translate("MainWindow", "F1"))
        self.label_25.setText(_translate("MainWindow", "F3"))
        self.label_17.setText(_translate("MainWindow", "F2"))
        self.Tab.setTabText(self.Tab.indexOf(self.Tab_tresholding), _translate("MainWindow", "Tresholding      "))
        self.Tab.setTabText(self.Tab.indexOf(self.Tab_generation), _translate("MainWindow", "Subset Generation  "))
        self.Tab.setTabText(self.Tab.indexOf(self.Preprocessing), _translate("MainWindow", "Preprocessing    "))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_dataset), _translate("MainWindow", "Dataset             "))
        self.Tab.setTabText(self.Tab.indexOf(self.tab), _translate("MainWindow", "Help                      "))
        self.pushButton.setText(_translate("MainWindow", "<"))
        self.pushButton_2.setText(_translate("MainWindow", "Act."))
        self.pushButton_3.setText(_translate("MainWindow", "Sav."))
        self.pushButton_4.setText(_translate("MainWindow", "Home."))
        self.label.setText(_translate("MainWindow", "  Prob.Stop                          "))
        self.label_2.setText(_translate("MainWindow", "  Prob.Supp "))
        self.label_3.setText(_translate("MainWindow", " Max.Attribute"))
        self.label_6.setText(_translate("MainWindow", " Max.Population"))
        self.label_7.setText(_translate("MainWindow", " Nb.Promotions"))
        self.label_8.setText(_translate("MainWindow", " Tol.Evolutivité"))
        self.label_4.setText(_translate("MainWindow", "                          Heurisitcs"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.delete_h.setText(_translate("MainWindow", "Delete"))
        self.heuristics_button.setText(_translate("MainWindow", "Add"))
        self.label_10.setText(_translate("MainWindow", "                          Strategies"))
        self.label_12.setText(_translate("MainWindow", "Prob.M"))
        self.label_14.setText(_translate("MainWindow", "Prob.O"))
        self.label_13.setText(_translate("MainWindow", "Prob.I"))
        self.label_11.setText(_translate("MainWindow", "Prob.C"))
        self.add_strategy.setText(_translate("MainWindow", "Add Strategy"))
        self.label_15.setText(_translate("MainWindow", "                        Training model"))
        self.label_39.setText(_translate("MainWindow", "                                  Ballot"))
        self.label_24.setText(_translate("MainWindow", "Tol                       "))
        self.menuFile.setTitle(_translate("MainWindow", "File  "))
        self.menuEdition.setTitle(_translate("MainWindow", "Edit  "))
        self.menuView.setTitle(_translate("MainWindow", "View  "))
        self.menuHelp.setTitle(_translate("MainWindow", "Help  "))


import image_fond


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
